config/routes.rb
# For details on the DSL available within this file, see
# http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  ######################## Public website routes ############################

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post],
        as: 'auth' # used by omniauth
  resources :collections, only: :index
  resources :elements, only: :index, param: :name
  match '/health', to: 'health#index', via: :get
  resources :items, only: [:index, :show] do
    match '/image', to: 'items#image', via: :get
  end
  match '/search', to: 'search#index', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  ############################ REST API routes ##############################

  namespace :api do
    match '/', to: redirect('/api/v1', status: 303), via: :all
    namespace :v1 do
      root 'landing#index'
      resources :elements, only: :index
      resources :harvests, only: [:create, :destroy, :update], param: :key
      resources :items, only: :update
    end
  end

  #################### Authentication-protected routes #######################

  namespace :admin do
    root 'dashboard#index'
    resources :boosts
    match '/configuration', to: 'configuration#index', via: :get
    match '/configuration', to: 'configuration#update', via: :patch
    resources :content_services, param: :key, path: 'content-services' do
      resources :element_mappings, path: 'element-mappings'
      match '/clear-element-mappings', to: 'content_services#clear_element_mappings',
            via: :delete, as: 'clear_element_mappings'
      match '/harvest', to: 'content_services#harvest', via: :post, as: 'harvest'
      match '/purge', to: 'content_services#purge', via: :post, as: 'purge'
    end
    resources :element_defs, path: 'elements', param: :name do
      resources :value_mappings, path: 'value-mappings'
      match '/usages', to: 'element_defs#usages', via: :get, as: 'usages'
    end
    match '/elements/import', to: 'element_defs#import', via: :post, as: 'element_defs_import'
    resources :harvests, param: :key, only: [:destroy, :index, :show] do
      match '/abort', to: 'harvests#abort', via: :patch, as: 'abort'
    end
    resources :items, only: :show do
      match '/purge-cached-images', to: 'items#purge_cached_item_images', via: :patch
    end
    resources :users, param: :username do
      match '/reset-api-key', to: 'users#reset_api_key', via: :post, as: 'reset_api_key'
    end
  end

  ############################## Root route ##################################

  if Rails.env.development?
    match '/', to: proc { [200, { "Content-Type": "text/html" }, [
      "<p>In development, this is a placeholder page. In all other
       environments, it redirects to <code>dls_url</code> (in the configuration)</p>
       <p><a href=\"/items\">Items</a></p>
       <p><a href=\"/admin\">Control Panel</a></p>"]] },
          via: :all, as: 'root'
  else
    match '/', to: redirect(Configuration.instance.dls_url, status: 303),
          via: :all, as: 'root'
  end


  # catch unknown routes
  match '*path', to: 'errors#not_found', via: :all

end

app/models/content_service.rb
# frozen_string_literal: true

class ContentService < ApplicationRecord

  SUPPORTED_IMAGE_TYPES = %w(image/jpeg image/png image/tiff)

  has_many :element_mappings, inverse_of: :content_service
  has_many :harvests, inverse_of: :content_service

  validates :key, presence: true, length: { maximum: 20 },
            uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: { maximum: 200 },
            uniqueness: { case_sensitive: false }
  validates_format_of :uri, with: URI.regexp,
                      message: 'is invalid', allow_blank: true

  after_initialize :init

  def init
    @num_items = -1
  end

  def ==(other)
    other.kind_of?(ContentService) and other.key == self.key
  end

  ##
  # Deletes all items associated with the service from the index.
  #
  # @return [void]
  # @see DeleteContentServiceItemsJob
  #
  def delete_all_items
    query = {
        query: {
            bool: {
                filter: [
                    {
                        term: {
                            Item::IndexFields::SERVICE_KEY => self.key
                        }
                    }
                ]
            }
        }
    }
    OpenSearchClient.instance.delete_by_query(
        query: JSON.generate(query),
        wait_for_completion: true)
  end

  ##
  # Deletes items associated with the service from the index if they are older
  # than the given age in days.
  #
  # @param days [Integer]
  # @return [void]
  #
  def delete_items_older_than(days)
    query = {
        query: {
            bool: {
                must: [
                    {
                        term: {
                            Item::IndexFields::SERVICE_KEY => self.key
                        }
                    },
                    {
                        range: {
                            Item::IndexFields::LAST_INDEXED => {
                                lte: days.days.ago.iso8601
                            }
                        }
                    }
                ]
            }
        }
    }
    OpenSearchClient.instance.delete_by_query(
        query: JSON.generate(query),
        wait_for_completion: true)
  end

  ##
  # @param element [Element]
  # @return [ElementDef]
  #
  def element_def_for_element(element)
    self.element_mappings.
        select{ |m| m.source_name == element.name}.first&.element_def
  end

  ##
  # Invokes [metaslurper](https://github.com/medusa-project/metaslurper) via
  # an AWS ECS Fargate task to harvest items.
  #
  # @param harvest [Harvest]
  # @return [void]
  # @raises [RuntimeError] if a harvest of this service is already in progress,
  #                        or if an incremental harvest is requested but a full
  #                        harvest hasn't been completed yet.
  #
  def harvest_items_async(harvest)
    unless Rails.env.production? or Rails.env.demo?
      raise 'This feature only works in production. '\
        'In development, invoke the harvester from the command line instead.'
    end

    if self.harvests.where(ended_at: nil).where('key != ?', harvest.key).count > 0
      raise 'Another harvest of this service is currently in progress.'
    end

    # https://github.com/medusa-project/metaslurper
    # N.B.: Multi-threaded harvesting is one of metaslurper's features, but
    # having more than four or so threads (across all concurrent harvests)
    # POSTing data back to the application at once can lead to write-block
    # exceptions in OpenSearch. The number of threads here is minimized in
    # order to go easy on our computing resources and increase the number of
    # possible concurrent harvests.
    command = ['java', '-jar', 'metaslurper.jar',
               '-source', self.key,
               '-sink', 'metaslurp',
               '-log_level', 'debug',
               '-threads', '2']
    # If the harvest is incremental, and this service has already been
    # harvested successfully, send the -incremental argument to the harvester
    # with the last successful harvest's ending epoch time.
    if harvest.incremental
      # Use created_at instead of ended_at because technically some content
      # could have changed between the two times.
      if self.last_completed_harvest&.created_at
        command << '-incremental'
        command << self.last_completed_harvest.created_at.to_i.to_s
      else
        raise 'Can\'t harvest this service incrementally until a full '\
            'harvest has been completed.'
      end
    end

    if harvest.max_num_items.to_i > 0
      command << '-max_entities'
      command << harvest.max_num_items.to_s
    end

    # https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECS/Client.html#run_task-instance_method
    config = Configuration.instance
    ecs = Aws::ECS::Client.new
    args = {
        cluster: config.ecs_cluster,
        task_definition: config.metaslurper_ecs_task_definition,
        launch_type: 'FARGATE',
        overrides: {
            container_overrides: [
                {
                    name: 'metaslurper',
                    command: command,
                    # Additive environment variable overrides to pass to
                    # metaslurper.
                    # Technically these aren't needed because the same info
                    # is already present in the task definition. It might be
                    # better to move all of that into this application's
                    # credentials, but that can wait for a rainy day.
                    environment: [
                        {
                            name: 'SERVICE_SINK_METASLURP_ENDPOINT',
                            value: config.root_url
                        },
                        {
                            name: 'SERVICE_SINK_METASLURP_USERNAME',
                            value: 'machine_user'
                        },
                        {
                            name: 'SERVICE_SINK_METASLURP_SECRET',
                            value: User.find_by_username('machine_user').api_key
                        },
                        {
                            name: 'SERVICE_SINK_METASLURP_HARVEST_KEY',
                            value: harvest.key
                        }
                    ]
                },
            ]
        },
        network_configuration: {
            awsvpc_configuration: {
                subnets: [config.ecs_subnet],
                security_groups: [config.ecs_security_group],
                assign_public_ip: 'ENABLED'
            },
        }
    }
    response = ecs.run_task(args)
    uuid = response.to_h[:tasks][0][:task_arn].split('/').last
    harvest.update!(ecs_task_uuid: uuid)
  end

  def hash
    self.key.hash
  end

  ##
  # @return [Harvest]
  #
  def last_completed_harvest
    self.harvests
        .where(status: Harvest::Status::SUCCEEDED)
        .order(created_at: :desc)
        .limit(1).first
  end

  ##
  # @return [Integer] The number of items contained in the service. The result
  #                   is cached.
  #
  def num_items
    if @num_items < 0
      @num_items = Item.search.
          content_service(self).
          aggregations(false).
          exclude_variants(Item::Variants::COLLECTION).
          limit(0).
          count
    end
    @num_items
  end

  def to_param
    self.key
  end

  def to_s
    self.name.present? ? "#{self.name}" : "#{self.key}"
  end

  ##
  # Adds new element mappings based on the given collection of source elements.
  # For example, if the collection contains `a`, `b`, and `c` elements, and the
  # instance already has mappings for `a` and `b`, then a `c` mapping will be
  # added.
  #
  # @param item_elements [Enumerable<Element>]
  # @return [void]
  #
  def update_element_mappings(item_elements)
    return if item_elements.empty?

    mappings = self.element_mappings

    item_elements.each do |item_element|
      unless mappings.find{ |m| m.source_name == item_element.name }
        mappings.build(source_name: item_element.name)
      end
    end
    self.save! rescue PG::UniqueViolation # this is OK as this method is not thread-safe
  end

end

app/controllers/admin/content_services_controller.rb
# frozen_string_literal: true

module Admin

  class ContentServicesController < ControlPanelController

    HARVEST_WINDOW_SIZE = 5

    before_action :load_model, only: [:destroy, :edit, :show, :update]
    before_action :require_admin, except: [:index, :show]

    ##
    # Responds to DELETE /admin/content-services/:id/element-mappings
    #
    def clear_element_mappings
      service = ContentService.find_by_key(params[:content_service_key])
      raise ActiveRecord::RecordNotFound unless service

      begin
        service.element_mappings.destroy_all
      rescue => e
        flash['error'] = "#{e}"
      else
        flash['success'] = 'Element mappings cleared. Reindex to '\
            'repopulate the element list.'
      ensure
        redirect_back fallback_location: admin_content_service_path(service)
      end
    end

    ##
    # Responds to POST /admin/content-services
    #
    def create
      begin
        service = ContentService.create!(sanitized_params)
      rescue => e
        handle_error(e)
        @content_service = ContentService.new
        render 'new'
      else
        flash['success'] = "Content service #{service} created."
        redirect_to admin_content_service_path(service)
      end
    end

    ##
    # Responds to DELETE /admin/content-services/:key
    #
    def destroy
      begin
        @content_service.destroy!
      rescue => e
        handle_error(e)
        redirect_to admin_content_services_url
      else
        flash['success'] = "Content service \"#{@content_service}\" deleted."
        redirect_to admin_content_services_url
      end
    end

    ##
    # Responds to GET /admin/content-services/:key/edit
    #
    def edit
    end

    ##
    # Responds to POST /admin/content-services/:key/harvest
    #
    def harvest
      @content_service = ContentService.find_by_key(params[:content_service_key])
      raise ActiveRecord::RecordNotFound unless @content_service

      begin
        harvest = Harvest.create!(content_service: @content_service,
                                  user: current_user,
                                  incremental: (params[:harvest_type] == 'incremental'),
                                  max_num_items: ::Configuration.instance.max_items_to_harvest)
        @content_service.harvest_items_async(harvest)

        flash['success'] = 'Harvesting will begin shortly.'
      rescue => e
        flash['error'] = "#{e}"
        harvest&.destroy!
      ensure
        redirect_back fallback_location: admin_content_service_path(@content_service)
      end
    end

    ##
    # Responds to GET /admin/content-services
    #
    def index
      @content_services = ContentService.order(:name)
    end

    ##
    # Responds to GET /admin/content-services/new
    #
    def new
      @content_service = ContentService.new
    end

    ##
    # Responds to POST /admin/content-services/:key/purge
    #
    def purge
      @content_service = ContentService.find_by_key(params[:content_service_key])
      raise ActiveRecord::RecordNotFound unless @content_service
      begin
        DeleteContentServiceItemsJob.perform_later(@content_service)
      rescue => e
        flash['error'] = "#{e}"
      else
        flash['success'] = "Purging all items from #{@content_service.name} "\
            "in the background. This may take a few minutes."
      ensure
        redirect_back fallback_location: admin_content_service_path(@content_service)
      end
    end

    ##
    # Responds to GET /admin/content-services/:key
    #
    def show
      @harvests = @content_service.harvests
                      .order(created_at: :desc)
                      .limit(HARVEST_WINDOW_SIZE)
    end

    ##
    # Responds to PATCH /admin/content-services/:key
    #
    def update
      begin
        @content_service.update!(sanitized_params)

        params[:content_service][:element_mappings]&.each do |k, v|
          ElementMapping.find(k).update!(element_def_id: v.values[0])
        end
      rescue => e
        handle_error(e)
        render 'edit'
      else
        flash['success'] = 'Content service updated. Note that if any '\
            'element mappings were changed, the service will need to be '\
            'reharvested.'
        redirect_to admin_content_service_path(@content_service)
      end
    end

    private

    def load_model
      @content_service = ContentService.find_by_key(params[:key])
      raise ActiveRecord::RecordNotFound unless @content_service
    end

    def sanitized_params
      params.require(:content_service).permit(:element_mappings,
                                              :harvest_type, :key, :name, :uri)
    end

  end

end

app/views/admin/content_services/_content_services.html.haml
%table.table
  %thead
    %tr
      %th{style: "min-width: 20%"} Name
      %th Key
      %th Items
      %th Last Harvest
  %tbody
    - @content_services.each do |service|
      %tr
        %td= link_to service.name, admin_content_service_path(service)
        %td
          %code= service.key
        %td= number_with_delimiter(service.num_items)
        %td
          - harvest = service.last_completed_harvest
          - if harvest&.ended_at
            = local_time_ago(harvest.ended_at)

app/views/admin/content_services/_form.html.haml
= form_for([:admin, @content_service]) do |f|
  = render 'admin/shared/error_messages', object: f.object
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :key
    = f.text_field :key, class: 'form-control', disabled: !f.object.new_record?
  .form-group
    = f.label :uri, 'URI'
    = f.text_field :uri, class: 'form-control'
  - unless f.object.new_record?
    %h2 Element Mappings
    %table.table.dl-elements
      %thead
        %tr
          %th Source Element
          %th= link_to 'Local Element', admin_element_defs_path, target: '_blank'
      %tbody
        - @content_service.element_mappings.order(:source_name).each do |mapping|
          %tr
            %td{style: "width:50%"}
              %code= mapping.source_name
            %td{style: "width:50%"}
              = select_tag "content_service[element_mappings][#{mapping.id}][element_def_id]", |
                options_from_collection_for_select(ElementDef.all.order(:name),                |
                                                   'id', 'label', mapping.element_def_id),     |
                include_blank: true,                                                           |
                class: 'custom-select'                                                         |
  .float-right
    = f.submit(f.object.new_record? ? 'Create Content Service' : 'Save Changes', |
      class: 'btn btn-primary mb-3')                                             |

app/views/admin/content_services/_harvest_modal.html.haml
-# Requires the following locals:
-#
-# content_service [ContentService]
-#

- last_completed = content_service.last_completed_harvest

#dl-harvest-modal.modal.fade{"aria-labelledby": "dl-harvest-modal-label", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      = form_tag(admin_content_service_harvest_path(content_service), method: :post) do
        .modal-header
          %h5#dl-harvest-modal-label.modal-title Harvest
          %button.close{"aria-label": "Close", "data-dismiss": "modal", type: "button"}
            %span{"aria-hidden": "true"}
        .modal-body
          - if Configuration.instance.max_items_to_harvest > 0
            .alert.alert-info
              %i.fa.fa-info-circle
              Only up to
              \#{number_with_delimiter(Configuration.instance.max_items_to_harvest)}
              entities will be harvested in this environment.
          .form-check
            %input#harvest-full.form-check-input{name: "harvest_type",
                                                 type: "radio",
                                                 value: "full",
                                                 checked: !last_completed}
            %label.form-check-label{for: "harvest-full"}
              Full
          .form-check
            %input#harvest-incremental.form-check-input{name: "harvest_type",
                                                        type: "radio",
                                                        value: "incremental",
                                                        checked: last_completed,
                                                        disabled: !last_completed}
            %label.form-check-label{for: "harvest-incremental"}
              - if last_completed
                Changes since #{local_time last_completed.created_at}
              - else
                Incremental (must complete a full harvest first)
        .modal-footer
          %button.btn.btn-light{"data-dismiss" => "modal", type: "button"} Cancel
          %button.btn.btn-primary{type: "submit"} Harvest

app/views/admin/content_services/edit.html.haml
- provide(:title, "Edit #{@content_service}")
- provide(:body_id, 'dl-admin-edit-content-service')
- provide :active_nav, 'content-services'

= breadcrumb({ label: 'Home', url: admin_root_path },                                  |
  { label: 'Content Services', url: admin_content_services_path },                     |
  { label: @content_service.name, url: admin_content_service_path(@content_service) }, |
  { label: 'Edit' })                                                                   |

%h1
  Edit #{@content_service.name}

= render partial: 'form', locals: { user: @content_service }

app/views/admin/content_services/index.html.haml
- provide :title, 'Content Services'
- provide :body_id, 'dl-admin-content-services'
- provide :active_nav, 'content-services'

- if current_user.medusa_admin?
  = button_bar({ label: 'New Content Service', |
    url: new_admin_content_service_path,       |
    icon: 'fa-plus' })                         |

%h1 Content Services
#dl-content-services
  = render 'content_services'

app/views/admin/content_services/new.html.haml
- provide(:title, 'New Content Service')
- provide(:body_id, 'dl-admin-new-content-service')
- provide :active_nav, 'content-services'

= breadcrumb({ label: 'Home', url: admin_root_path },              |
  { label: 'Content Services', url: admin_content_services_path }, |
  { label: 'New Content Service' })                                |

%h1 New Content Service
= render partial: 'form', locals: { content_service: @content_service }

app/views/admin/content_services/show.html.haml
- provide :title, @content_service
- provide :body_id, 'dl-admin-content-service'
- provide :active_nav, 'content-services'

= breadcrumb({ label: 'Home', url: admin_root_path },              |
  { label: 'Content Services', url: admin_content_services_path }, |
  { label: @content_service.name })                                |

- if current_user.medusa_admin?
  .btn-group.float-right{role: "group"}
    .btn-group{role: "group"}
      %button#btnGroupDrop1.btn.btn-light.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", type: "button"}
        Items
      .dropdown-menu{"aria-labelledby" => "btnGroupDrop1"}
        %a.dropdown-item{"data-target" => "#dl-harvest-modal", "data-toggle" => "modal", href: "#"}
          %i.fas.fa-sync
          Harvest
        = link_to admin_content_service_purge_path(@content_service),
          class: 'dropdown-item', method: 'post',
          data: { confirm: 'Are you sure you want to purge all items from this content service? This cannot be undone.' } do
          %i.fas.fa-trash
          Purge
    = link_to(edit_admin_content_service_path(@content_service),
              class: 'btn btn-light') do
      %i.fas.fa-edit
      Edit
    -# the test service can't be deleted as it's required for metaslurper tests
    = link_to(admin_content_service_path(@content_service),
              class: 'btn btn-danger',
              method: 'delete',
              disabled: (@content_service.key == 'test'),
              data: { confirm: 'Are you sure you want to delete this content service? This cannot be undone.' }) do
      %i.fas.fa-trash
      Delete

%h1= @content_service.name
.row
  .col-sm-4
    %dl
      %dt URI
      %dd= @content_service.uri.present? ? link_to(@content_service.uri, @content_service.uri) : 'None'
      %dt Key
      %dd
        %code= @content_service.key
      %dt Items
      %dd= number_with_delimiter(@content_service.num_items)
      - if @harvests.any?
        %dt
          Last #{Admin::ContentServicesController::HARVEST_WINDOW_SIZE} Harvests
        %dd
          %ol
            - @harvests.each do |harvest|
              %li
                = link_to(local_time(harvest.updated_at), admin_harvest_path(harvest))
                = harvest_status_badge(harvest.status)
  .col-sm-8
    - if current_user.medusa_admin?
      = button_bar({ label: 'Clear Element Mappings',                             |
        icon: 'fa-times',                                                         |
        url: admin_content_service_clear_element_mappings_path(@content_service), |
        method: 'delete',                                                         |
        class: 'btn-danger btn-sm',                                               |
        confirm: 'Are you sure you want to clear the element mappings?' })        |
    %h2 Elements
    %table.table.table-striped
      %tr
        %th
        %th
          Source Element
          %br/
          %span.text-muted (autodetected during indexing)
        %th= link_to 'Local Element', admin_element_defs_path, target: '_blank'
        %th Local Element Data Type
        %th Local Element Usages (TSV)
      - @content_service.element_mappings.order(:source_name).each do |mapping|
        %tr
          %td
            - if current_user.medusa_admin?
              = link_to(admin_content_service_element_mapping_path(@content_service, mapping),
                class: 'btn btn-danger btn-sm',
                method: :delete,
                data: { confirm: 'Are you sure you want to delete this element mapping?' }) do
                %i.fas.fa-times
                Remove
          %td
            %code= mapping.source_name
          %td= mapping.element_def&.label
          %td= ElementDef::DataType::to_s(mapping.element_def&.data_type)
          %td
            - element = mapping.element_def
            - if element
              - num_usages = element.num_usages(@content_service)
              - if num_usages > 0
                = link_to(number_with_delimiter(num_usages),
                          admin_element_def_usages_path(element,
                          content_service_key: @content_service.key))

= render partial: 'harvest_modal',
         locals: { content_service: @content_service }