config/routes.rb
# For details on the DSL available within this file, see
# http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  ######################## Public website routes ############################

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post],
        as: 'auth' # used by omniauth
  resources :collections, only: :index
  resources :elements, only: :index, param: :name
  match '/health', to: 'health#index', via: :get
  resources :items, only: [:index, :show] do
    match '/image', to: 'items#image', via: :get
  end
  match '/search', to: 'search#index', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  ############################ REST API routes ##############################

  namespace :api do
    match '/', to: redirect('/api/v1', status: 303), via: :all
    namespace :v1 do
      root 'landing#index'
      resources :elements, only: :index
      resources :harvests, only: [:create, :destroy, :update], param: :key
      resources :items, only: :update
    end
  end

  #################### Authentication-protected routes #######################

  namespace :admin do
    root 'dashboard#index'
    resources :boosts
    match '/configuration', to: 'configuration#index', via: :get
    match '/configuration', to: 'configuration#update', via: :patch
    resources :content_services, param: :key, path: 'content-services' do
      resources :element_mappings, path: 'element-mappings'
      match '/clear-element-mappings', to: 'content_services#clear_element_mappings',
            via: :delete, as: 'clear_element_mappings'
      match '/harvest', to: 'content_services#harvest', via: :post, as: 'harvest'
      match '/purge', to: 'content_services#purge', via: :post, as: 'purge'
    end
    resources :element_defs, path: 'elements', param: :name do
      resources :value_mappings, path: 'value-mappings'
      match '/usages', to: 'element_defs#usages', via: :get, as: 'usages'
    end
    match '/elements/import', to: 'element_defs#import', via: :post, as: 'element_defs_import'
    resources :harvests, param: :key, only: [:destroy, :index, :show] do
      match '/abort', to: 'harvests#abort', via: :patch, as: 'abort'
    end
    resources :items, only: :show do
      match '/purge-cached-images', to: 'items#purge_cached_item_images', via: :patch
    end
    resources :users, param: :username do
      match '/reset-api-key', to: 'users#reset_api_key', via: :post, as: 'reset_api_key'
    end
  end

  ############################## Root route ##################################

  if Rails.env.development?
    match '/', to: proc { [200, { "Content-Type": "text/html" }, [
      "<p>In development, this is a placeholder page. In all other
       environments, it redirects to <code>dls_url</code> (in the configuration)</p>
       <p><a href=\"/items\">Items</a></p>
       <p><a href=\"/admin\">Control Panel</a></p>"]] },
          via: :all, as: 'root'
  else
    match '/', to: redirect(Configuration.instance.dls_url, status: 303),
          via: :all, as: 'root'
  end


  # catch unknown routes
  match '*path', to: 'errors#not_found', via: :all

end

app/controllers/api/v1/landing_controller.rb
# frozen_string_literal: true

module Api

  module V1

    class LandingController < ApiController

      ##
      # Responds to GET /api/v1
      #
      def index
        @version_path_component = 'v1'
      end

    end

  end

end

app/views/landing/index.html.erb
<% provide(:body_id, 'landing') %>

<% row1_crop = { width: 3000, height: 400 } %>
<% rown_crop = { width: 1500, height: 400 } %>

<div id="dl-banner">
  <h1><span>Digital Collections</span></h1>

  <div class="row justify-content-sm-center">
    <div class="col-sm-8 col-md-7 col-lg-6">
      <%= form_tag(search_path, method: :get, enforce_utf8: false, id: 'dl-search') do %>
        <div class="input-group mb-4">
          <%= search_field_tag(:q, '',
                               placeholder: raw("Search across #{number_with_delimiter(@num_items)} items&hellip;"),
                               'aria-label': 'Search',
                               class: 'form-control form-control-lg') %>
          <div class="input-group-append">
            <input type="submit" value="Search" class="btn btn-primary">
          </div>
          <div class="input-group-append dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button"
                    id="dl-browse-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Browse
            </button>
            <div class="dropdown-menu" aria-labelledby="dl-browse-dropdown">
              <%= link_to 'Collections', collections_path('fq[]': 'system_keyword_service_key:dls'), class: 'dropdown-item' %>
              <%= link_to 'Items', items_path, class: 'dropdown-item' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <% if @services[:dls] %>
    <div class="col-md-12">
      <div class="card bg-dark text-white">
        <%= thumbnail_for(@services[:dls],
                          crop: row1_crop,
                          class: 'card-img-top d-none d-lg-block',
                          alt: "Thumbnail for #{@services[:dls]}") %>
        <%= thumbnail_for(@services[:dls],
                          crop: { width: row1_crop[:width] / 2.0, height: row1_crop[:height] },
                          class: 'card-img-top d-lg-none',
                          alt: "Thumbnail for #{@services[:dls]}") %>
        <div class="card-img-overlay d-flex flex-column justify-content-end">
          <div class="dl-card-text-backdrop">
            <h5 class="card-title">
              <%= link_to 'Digital Special Collections', @services[:dls].uri %>
            </h5>
            <p class="card-text d-none d-sm-block">
              <%= @services[:dls].description %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <% if @services[:ideals] %>
    <div class="col-lg-6">
      <div class="card bg-dark text-white">
        <%= thumbnail_for(@services[:ideals],
                          crop: rown_crop,
                          class: 'card-img-top',
                          alt: "Thumbnail for #{@services[:ideals]}") %>
        <div class="card-img-overlay d-flex flex-column justify-content-end">
          <div class="dl-card-text-backdrop">
            <h5 class="card-title">
              <%= link_to 'Scholarship', @services[:ideals].uri %>
            </h5>
            <p class="card-text d-none d-sm-block">
              <%= @services[:ideals].description %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if @services[:book] %>
    <div class="col-lg-6">
      <div class="card bg-dark text-white">
        <%= thumbnail_for(@services[:book],
                          crop: rown_crop,
                          class: 'card-img-top',
                          alt: "Thumbnail for #{@services[:book]}") %>
        <div class="card-img-overlay d-flex flex-column justify-content-end">
          <div class="dl-card-text-backdrop">
            <h5 class="card-title">
              <%= link_to 'Digitized Books',
                          items_path('fq[]': 'system_keyword_service_key:book') %>
            </h5>
            <p class="card-text d-none d-sm-block">
              <%= @services[:book].description %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <% if @services[:databank] %>
    <div class="col-lg-6">
      <div class="card bg-dark text-white">
        <%= thumbnail_for(@services[:databank],
                          crop: rown_crop,
                          class: 'card-img-top',
                          alt: "Thumbnail for #{@services[:databank]}") %>
        <div class="card-img-overlay d-flex flex-column justify-content-end">
          <div class="dl-card-text-backdrop">
            <h5 class="card-title">
              <%= link_to 'Research Data', @services[:databank].uri %>
            </h5>
            <p class="card-text d-none d-sm-block">
              <%= @services[:databank].description %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if @services[:idnc] %>
    <div class="col-lg-6">
      <div class="card bg-dark text-white">
        <%= thumbnail_for(@services[:idnc],
                          crop: rown_crop,
                          class: 'card-img-top',
                          alt: "Thumbnail for #{@services[:idnc]}") %>
        <div class="card-img-overlay d-flex flex-column justify-content-end">
          <div class="dl-card-text-backdrop">
            <h5 class="card-title">
              <%= link_to 'Digitized Newspapers', @services[:idnc].uri %>
            </h5>
            <p class="card-text d-none d-sm-block">
              <%= @services[:idnc].description %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>