config/routes.rb
# For details on the DSL available within this file, see
# http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  ######################## Public website routes ############################

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post],
        as: 'auth' # used by omniauth
  resources :collections, only: :index
  resources :elements, only: :index, param: :name
  match '/health', to: 'health#index', via: :get
  resources :items, only: [:index, :show] do
    match '/image', to: 'items#image', via: :get
  end
  match '/search', to: 'search#index', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  ############################ REST API routes ##############################

  namespace :api do
    match '/', to: redirect('/api/v1', status: 303), via: :all
    namespace :v1 do
      root 'landing#index'
      resources :elements, only: :index
      resources :harvests, only: [:create, :destroy, :update], param: :key
      resources :items, only: :update
    end
  end

  #################### Authentication-protected routes #######################

  namespace :admin do
    root 'dashboard#index'
    resources :boosts
    match '/configuration', to: 'configuration#index', via: :get
    match '/configuration', to: 'configuration#update', via: :patch
    resources :content_services, param: :key, path: 'content-services' do
      resources :element_mappings, path: 'element-mappings'
      match '/clear-element-mappings', to: 'content_services#clear_element_mappings',
            via: :delete, as: 'clear_element_mappings'
      match '/harvest', to: 'content_services#harvest', via: :post, as: 'harvest'
      match '/purge', to: 'content_services#purge', via: :post, as: 'purge'
    end
    resources :element_defs, path: 'elements', param: :name do
      resources :value_mappings, path: 'value-mappings'
      match '/usages', to: 'element_defs#usages', via: :get, as: 'usages'
    end
    match '/elements/import', to: 'element_defs#import', via: :post, as: 'element_defs_import'
    resources :harvests, param: :key, only: [:destroy, :index, :show] do
      match '/abort', to: 'harvests#abort', via: :patch, as: 'abort'
    end
    resources :items, only: :show do
      match '/purge-cached-images', to: 'items#purge_cached_item_images', via: :patch
    end
    resources :users, param: :username do
      match '/reset-api-key', to: 'users#reset_api_key', via: :post, as: 'reset_api_key'
    end
  end

  ############################## Root route ##################################

  if Rails.env.development?
    match '/', to: proc { [200, { "Content-Type": "text/html" }, [
      "<p>In development, this is a placeholder page. In all other
       environments, it redirects to <code>dls_url</code> (in the configuration)</p>
       <p><a href=\"/items\">Items</a></p>
       <p><a href=\"/admin\">Control Panel</a></p>"]] },
          via: :all, as: 'root'
  else
    match '/', to: redirect(Configuration.instance.dls_url, status: 303),
          via: :all, as: 'root'
  end


  # catch unknown routes
  match '*path', to: 'errors#not_found', via: :all

end

app/models/element.rb
# frozen_string_literal: true

##
# "Abstract" base class for LocalElements and SourceElements.
#
class Element

  attr_accessor :name, :value

  def initialize(args = {})
    args.each do |k,v|
      instance_variable_set("@#{k}", v) unless v.nil?
    end
  end

  def ==(obj)
    obj.object_id == self.object_id || (obj.kind_of?(Element) and
        obj.name == self.name and obj.value == self.value)
  end

  ##
  # @return [Hash]
  #
  def as_json(options = {})
    struct = super(options)
    struct['name'] = self.name
    struct['value'] = self.value
    struct
  end

  def hash
    [self.name, self.value].hash
  end

  ##
  # @return [String] The value.
  #
  def to_s
    "#{self.value}"
  end

  ##
  # @return [void]
  # @raises [ArgumentError] if the instance is invalid.
  #
  def validate
    raise ArgumentError, 'Missing name' if self.name.blank?
    raise ArgumentError, 'Invalid name' if self.name.blank?
    raise ArgumentError, 'Missing value' if self.value.blank?
  end

end

app/controllers/admin/elements_controller.rb
module Admin

  class ElementsController < ControlPanelController

    class ImportMode
      MERGE = 'merge'
      REPLACE = 'replace'
    end

    PERMITTED_PARAMS = [:description, :facetable, :index, :label, :name,
                        :searchable, :sortable]

    before_action :set_permitted_params
    before_action :require_admin, except: :index

    ##
    # XHR only
    #
    def create
      @element = Element.new(sanitized_params)
      begin
        @element.save!
      rescue ActiveRecord::RecordInvalid
        response.headers['X-Kumquat-Result'] = 'error'
        render partial: 'shared/validation_messages',
               locals: { entity: @element }
      rescue => e
        handle_error(e)
        keep_flash
        render 'create'
      else
        response.headers['X-Kumquat-Result'] = 'success'
        flash['success'] = "Element \"#{@element.name}\" created."
        keep_flash
        render 'create' # create.js.erb will reload the page
      end
    end

    def destroy
      element = Element.find_by_name(params[:name])
      raise ActiveRecord::RecordNotFound unless element
      begin
        element.destroy!
      rescue => e
        handle_error(e)
      else
        flash['success'] = "Element \"#{element.name}\" deleted."
      ensure
        redirect_back fallback_location: admin_elements_path
      end
    end

    ##
    # XHR only
    #
    def edit
      element = Element.find_by_name(params[:name])
      raise ActiveRecord::RecordNotFound unless element

      render partial: 'admin/elements/form',
             locals: { element: element, context: :edit }
    end

    ##
    # Responds to POST /admin/elements/import
    #
    def import
      begin
        raise 'No elements specified.' if params[:elements].blank?

        json = params[:elements].read.force_encoding('UTF-8')
        struct = JSON.parse(json)
        ActiveRecord::Base.transaction do
          if params[:import_mode] == ImportMode::REPLACE
            Element.delete_all # skip callbacks & validation
          end
          struct.each do |hash|
            e = Element.find_by_name(hash['name'])
            if e
              e.update_from_json_struct(hash)
            else
              Element.from_json_struct(hash).save!
            end
          end
        end
      rescue => e
        handle_error(e)
        redirect_to admin_elements_path
      else
        flash['success'] = "#{struct.length} elements created or updated."
        redirect_to admin_elements_path
      end
    end

    ##
    # Responds to GET /elements
    #
    def index
      respond_to do |format|
        format.html do
          @elements = Element.all.order(:index)
          @new_element = Element.new
        end
        format.json do
          @elements = Element.all.order(:name)
          headers['Content-Disposition'] = 'attachment; filename=elements.json'
          render plain: JSON.pretty_generate(@elements.as_json)
        end
      end
    end

    ##
    # XHR only
    #
    def update
      element = Element.find_by_name(params[:name])
      raise ActiveRecord::RecordNotFound unless element

      begin
        element.update!(sanitized_params)
      rescue ActiveRecord::RecordInvalid
        render partial: 'shared/validation_messages',
               locals: { entity: element }
      rescue => e
        handle_error(e)
        keep_flash
        render 'update'
      else
        flash['success'] = "Element \"#{element.name}\" updated."
        keep_flash
        render 'update' # update.js.erb will reload the page
      end
    end

    private

    def sanitized_params
      params.require(:element).permit(PERMITTED_PARAMS)
    end

    def set_permitted_params
      @permitted_params = params.permit(PERMITTED_PARAMS)
    end

  end

end

app/controllers/api/v1/elements_controller.rb
# frozen_string_literal: true

module Api

  module V1

    class ElementsController < ApiController

      ##
      # Responds to GET /api/v1/elements
      #
      def index
        @start = params[:start].to_i
        @limit = params[:limit].to_i
        @limit = DEFAULT_RESULTS_LIMIT if @limit < 1
        @limit = MAX_RESULTS_LIMIT if @limit > MAX_RESULTS_LIMIT

        @elements = ElementDef.all.order(:name).limit(@limit).offset(@start)

        render json: {
            start: @start,
            limit: @limit,
            numResults: @count,
            results: @elements
        }
      end

    end

  end

end

app/controllers/elements_controller.rb
# frozen_string_literal: true

class ElementsController < ApplicationController

  protect_from_forgery with: :null_session

  ##
  # Responds to GET /elements (JSON only)
  #
  def index
    render json: ElementDef.all.order(:name).map { |e|
      {
          name:               e.name,
          label:              e.label,
          data_type:          ElementDef::DataType::to_s(e.data_type),
          searchable:         e.searchable,
          sortable:           e.sortable,
          facetable:          e.facetable,
          indexed_sort_field: e.sortable ? e.indexed_sort_field : nil
      }
    }
  end

end

app/views/admin/elements/_add_modal.html.erb
<%
# @param element [Element]
# @param context [Symbol] :new or :edit
%>

<!-- Add-element modal -->
<div class="modal fade" id="dl-add-element-modal" tabindex="-1" role="dialog"
     aria-labelledby="dl-add-element-modal-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="dl-add-element-modal-label">Add Element</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: 'form', locals: { element: element,
                                              context: context } %>
      </div>
    </div>
  </div>
</div>

app/views/admin/elements/_form.html.erb
<%
  # @param element [Element]
  # @param context [Symbol] :new or :edit

  position_options_for_select = [['Nothing (First)', 0]]
  elements = Element.order(:index)
  if element.id.present?
    elements = elements.where('id != ?', element.id)
  end
  elements.each_with_index do |e, i|
    position_options_for_select << [e.label, i + 1]
  end
%>

<%= form_for([:admin, element], remote: true) do |f| %>
  <div class="dl-error-messages">
    <% # populated via ajax by shared/_validation_messages.js.erb
    %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <% if context == :new %>
      <%= f.text_field :name, class: 'form-control' %>
    <% else %>
      <br>
      <%= element.name %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :label %>
    <%= f.text_field :label, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :index, 'Position After' %>
    <%= f.select :index, position_options_for_select,
                 { selected: element.index },
                 class: 'form-control' %>
  </div>

  <div class="checkbox">
    <label>
      <%= f.check_box :searchable %>
      Searchable
    </label>
  </div>

  <div class="checkbox">
    <label>
      <%= f.check_box :sortable %>
      Sortable
    </label>
  </div>

  <div class="checkbox">
    <label>
      <%= f.check_box :facetable %>
      Facetable
    </label>
  </div>

  <div class="clearfix">
    <div class="pull-right">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      <%= f.submit(context == :new ? 'Create Element' : 'Edit Element',
                   class: 'btn btn-primary') %>
    </div>
  </div>
<% end %>

app/views/admin/elements/_import_modal.html.erb
<!-- Import-elements modal -->
<div class="modal fade" id="dl-import-modal" tabindex="-1" role="dialog"
     aria-labelledby="dl-import-modal-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_tag(admin_elements_import_path(format: :json),
                   { multipart: true }) do %>
          <div class="modal-header">
            <h5 class="modal-title" id="dl-import-modal-label">Import Elements</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <%= file_field_tag('elements') %>

            <hr>

            <div class="radio">
              <label>
                <%= radio_button_tag('import_mode',
                                     Admin::ElementsController::ImportMode::MERGE, true,
                                     'aria-described-by' => 'dl-merge-help') %>
                Merge
              </label>
              <span id="dl-merge-help" class="help-block">
              Create any new elements, and update existing elements, but don't
              delete anything.
            </span>
            </div>

            <div class="radio">
              <label>
                <%= radio_button_tag('import_mode',
                                     Admin::ElementsController::ImportMode::REPLACE, false,
                                     'aria-described-by' => 'dl-only-create-help') %>
                Replace
              </label>
              <span id="dl-only-create-help" class="help-block">
              Replace the current set of elements with the ones being imported.
            </span>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Import</button>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/elements/index.html.erb
<% provide :title, 'Elements' %>
<% provide :body_id, 'admin_elements' %>
<% provide :active_nav, 'entities' %>

<% if current_user.admin? %>
  <%= button_bar({ type: 'button',
                   label: 'Add Element',
                   'data-toggle': 'modal',
                   'data-target': '#dl-add-element-modal',
                   icon: 'fa-plus' },
                 { type: 'button',
                   label: 'Import&hellip;',
                   'data-toggle': 'modal',
                   'data-target': '#dl-import-modal',
                   icon: 'fa-upload' },
                 { label: 'Export',
                   icon: 'fa-download',
                   url: @permitted_params.merge(format: 'json') }) %>
<% end %>

<h1>Elements</h1>

<table class="table">
  <thead>
    <tr>
      <th style="width: 1px"></th>
      <th style="width: 1px"></th>
      <th>Name</th>
      <th>Label</th>
      <th>Description</th>
      <th>Searchable</th>
      <th>Sortable</th>
      <th>Facetable</th>
    </tr>
  </thead>
  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td>
          <% if current_user.admin? %>
            <button type="button" class="btn btn-default btn-sm dl-edit-element"
                    data-toggle="modal" data-target="#dl-edit-element-modal"
                    data-element-name="<%= element.name %>">
              <i class="fa fa-pencil"></i> Edit
            </button>
          <% end %>
        </td>
        <td>
          <% if current_user.admin? %>
            <%= link_to admin_element_path(element),
                        class: 'btn btn-danger btn-sm', method: :delete,
                        data: { confirm: 'Are you sure you want to delete '\
                        'this element?' } do %>
               <i class="fa fa-trash"></i> Delete
            <% end %>
          <% end %>
        </td>
        <td><code><%= element.name %></code></td>
        <td><%= element.label %></td>
        <td><%= element.description %></td>
        <td class="text-center <%= element.searchable ? 'bg-success' : 'bg-danger' %>">
          <%= boolean(element.searchable) %>
        </td>
        <td class="text-center <%= element.sortable ? 'bg-success' : 'bg-danger' %>">
          <%= boolean(element.sortable) %>
        </td>
        <td class="text-center <%= element.facetable ? 'bg-success' : 'bg-danger' %>">
          <%= boolean(element.facetable) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: 'add_modal', locals: { element: @new_element,
                                           context: :new } %>
<%= render partial: 'edit_modal' %>
<%= render partial: 'import_modal' %>