config/routes.rb
# For details on the DSL available within this file, see
# http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  ######################## Public website routes ############################

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post],
        as: 'auth' # used by omniauth
  resources :collections, only: :index
  resources :elements, only: :index, param: :name
  match '/health', to: 'health#index', via: :get
  resources :items, only: [:index, :show] do
    match '/image', to: 'items#image', via: :get
  end
  match '/search', to: 'search#index', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  ############################ REST API routes ##############################

  namespace :api do
    match '/', to: redirect('/api/v1', status: 303), via: :all
    namespace :v1 do
      root 'landing#index'
      resources :elements, only: :index
      resources :harvests, only: [:create, :destroy, :update], param: :key
      resources :items, only: :update
    end
  end

  #################### Authentication-protected routes #######################

  namespace :admin do
    root 'dashboard#index'
    resources :boosts
    match '/configuration', to: 'configuration#index', via: :get
    match '/configuration', to: 'configuration#update', via: :patch
    resources :content_services, param: :key, path: 'content-services' do
      resources :element_mappings, path: 'element-mappings'
      match '/clear-element-mappings', to: 'content_services#clear_element_mappings',
            via: :delete, as: 'clear_element_mappings'
      match '/harvest', to: 'content_services#harvest', via: :post, as: 'harvest'
      match '/purge', to: 'content_services#purge', via: :post, as: 'purge'
    end
    resources :element_defs, path: 'elements', param: :name do
      resources :value_mappings, path: 'value-mappings'
      match '/usages', to: 'element_defs#usages', via: :get, as: 'usages'
    end
    match '/elements/import', to: 'element_defs#import', via: :post, as: 'element_defs_import'
    resources :harvests, param: :key, only: [:destroy, :index, :show] do
      match '/abort', to: 'harvests#abort', via: :patch, as: 'abort'
    end
    resources :items, only: :show do
      match '/purge-cached-images', to: 'items#purge_cached_item_images', via: :patch
    end
    resources :users, param: :username do
      match '/reset-api-key', to: 'users#reset_api_key', via: :post, as: 'reset_api_key'
    end
  end

  ############################## Root route ##################################

  if Rails.env.development?
    match '/', to: proc { [200, { "Content-Type": "text/html" }, [
      "<p>In development, this is a placeholder page. In all other
       environments, it redirects to <code>dls_url</code> (in the configuration)</p>
       <p><a href=\"/items\">Items</a></p>
       <p><a href=\"/admin\">Control Panel</a></p>"]] },
          via: :all, as: 'root'
  else
    match '/', to: redirect(Configuration.instance.dls_url, status: 303),
          via: :all, as: 'root'
  end


  # catch unknown routes
  match '*path', to: 'errors#not_found', via: :all

end

app/views/layouts/admin/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark
  %button.navbar-toggler{"aria-controls": "dl-navbar-left-collapse",
                         "aria-expanded": "false",
                         "aria-label": "Toggle navigation",
                         "data-target": "#dl-navbar-left-collapse",
                         "data-toggle": "collapse",
                         type: "button"}
    %span.navbar-toggler-icon
  #dl-navbar-left-collapse.collapse.navbar-collapse
    %ul.navbar-nav
      %li#cr-nav.nav-item
        = link_to('Collection Registry', Configuration.instance.collection_registry_url, class: 'nav-link')
      %li#dl-nav.nav-item
        = link_to('Digital Library', Configuration.instance.dls_url + '/admin', class: 'nav-link')
      %li#gateway-nav.nav-item.active
        = link_to('Metadata Gateway', '#', class: 'nav-link')
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  = link_to(admin_root_path, class: 'navbar-brand') do
    %i.fas.fa-tachometer-alt
  %button.navbar-toggler{"aria-controls": "dl-navbar-right-collapse",
                         "aria-expanded": "false",
                         "aria-label": "Toggle navigation",
                         "data-target": "#dl-navbar-right-collapse",
                         "data-toggle": "collapse",
                         type: "button"}
    %span.navbar-toggler-icon
  #dl-navbar-right-collapse.collapse.navbar-collapse
    %ul.navbar-nav
      %li#elements-nav.nav-item
        = link_to('Elements', admin_element_defs_path, class: 'nav-link')
      %li#content-services-nav.nav-item
        = link_to('Content Services', admin_content_services_path, class: 'nav-link')
      %li#harvests-nav.nav-item
        = link_to('Harvests', admin_harvests_path, class: 'nav-link')
      - if current_user.medusa_admin?
        %li#server-nav.nav-item.dropdown
          %a#dl-server-menu-toggle.nav-link.dropdown-toggle{"aria-expanded": "false",
                                                            "aria-haspopup": "true",
                                                            "data-toggle": "dropdown",
                                                            href: "#"}
            Server
          .dropdown-menu{"aria-labelledby": "dl-server-menu-toggle"}
            = link_to('Configuration', admin_configuration_path, class: 'dropdown-item')
            = link_to('Boosts', admin_boosts_path, class: 'dropdown-item')
            = link_to('Users', admin_users_path, class: 'dropdown-item')
            .dropdown-divider
            = link_to('HTTP API', api_url, class: 'dropdown-item')
    %ul.navbar-nav.ml-md-auto
      %li.nav-item
        = link_to('https://wiki.illinois.edu/wiki/display/scrs/Search+Gateway',
                  class: 'nav-link', target: '_blank') do
          %i.fa.fa-question-circle
      %li.nav-item.dropdown
        %a#dl-user-menu-toggle.nav-link.dropdown-toggle{"aria-expanded": "false",
                                                        "aria-haspopup": "true",
                                                        "data-toggle": "dropdown",
                                                        href: "#"}
          %i.fas.fa-user{"aria-hidden": "true"}
          = current_user.username
        .dropdown-menu.dropdown-menu-right{"aria-labelledby": "dl-user-menu-toggle"}
          = link_to 'Log Out', signout_path, method: :delete, class: 'dropdown-item'

app/views/layouts/admin/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = yield(:title)
      | UIUC Library Digital Collections Search Gateway Control Panel
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/
    = csrf_meta_tags
    = stylesheet_link_tag 'admin/application', media: 'all'
    = javascript_include_tag 'admin/application'
    = render partial: 'layouts/font_awesome'
    = content_for :head
  %body.dl-admin{id: yield(:body_id).present? ? yield(:body_id) : nil,
                 'active_nav': yield(:active_nav)}
    = render partial: 'layouts/admin/header'
    .container-fluid
      = hidden_field_tag('dl-root-url', root_url(protocol: (Rails.env.production? or Rails.env.demo?) ? :https : :http))
      = hidden_field_tag('dl-root-path', root_path)
      = hidden_field_tag('dl-current-path', request.fullpath)
      .page-content
        = flashes
        = yield.force_encoding(Encoding::UTF_8)
    %footer